language: node_js

node_js: "node"

before_script:
  - npm install -g truffle@4.1.14 ganache-cli@6.1.8
  - npm install

script:
  - ganache-cli -m "they only media any modify banner suffer pole tag rule creek harvest" > /dev/null &
  - sleep 5
  - truffle migrate
  - truffle test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
